config/routes.rb
Rails.application.routes.draw do
  
 
  devise_for :users
  devise_for :employees, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :pages
  resources :quote
  resources :leads
  # resources :interventions 
  # root to: 'geolocalisation#index'
  root 'leads#new'

  get 'index' => 'leads#new' # index
  get 'corporate' => 'pages#corporate' # corporate
  get 'residential' => 'pages#residential' # residential
  get 'quoteform' => 'quote#new' # quote form
  get 'login' => 'pages#login'
  get 'sign_up' => 'users#sign_up'
  get 'sign_in' => 'users#sign_in'
  get 'leads' => 'leads#new'

  get 'welcome' => 'watson#welcome'
  get 'geolocalisation/index'
  get 'interventions/index'
  get 'interventions' => 'interventions#index'


  resources :interventions do
    get :get_building, on: :collection
    get :get_battery, on: :collection
    get :get_column, on: :collection
    get :get_elevator, on: :collection
  end
  # namespace :admin do
  #   resources :addresses do
  #     resources :customers do
  #       resources :buildings do
  #         resources :building_details
  #       end
  #     end
  #   end
  # end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rocket Elevators</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta charset="utf-8" />
	  <meta name="description" content="" />
	  <meta name="Author" content="J.L." />

    <!-- mobile settings -->
    <meta name="viewport" content="width=device-width, maximum-scale=1, initial-scale=1, user-scalable=0" />
    <!--[if IE]><meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'><![endif]-->

    <!-- WEB FONTS : use %7C instead of | (pipe)
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600%7CRaleway:300,400,500,600,700%7CLato:300,400,400italic,600,700" rel="stylesheet" type="text/css" />
    <link href="https://fonts.google.com/specimen/Roboto" rel="stylesheet" type="text/css" />
      -->
    <!--<%= stylesheet_link_tag "https://fonts.googleapis.com/css?family=Open+Sans:300,400,600%7CRaleway:300,400,500,600,700%7CLato:300,400,400italic,600,700" %>
		 <%= stylesheet_link_tag "https://fonts.googleapis.com/css?family=Roboto&display=swap" %>-->
 <!-- refer to the repository for code  google map -->
 
  <body>
    <%= stylesheet_link_tag "essentials" %>
    <%= stylesheet_link_tag "layout" %>

    <%= stylesheet_link_tag "header-1" %>
    <%= stylesheet_link_tag "blue" %>
   
    <style>
      html * {
        font-family: 'Roboto','FontAwesome' !important;
      }
		</style>
  </head>
 
  <body class="smoothscroll enable-animation grain-blue">
    <div id="header" class="navbar-toggleable-md sticky clearfix">
      <!-- TOP NAV -->
      <header id="topNav">
        <div class="container">

          <!-- Mobile Menu Button -->
          <button class="btn btn-mobile" data-toggle="collapse" data-target=".nav-main-collapse">
            <i class="fa fa-bars"></i>
          </button>

          <!-- Logo -->
          <%= link_to image_tag("R2", :alt => "Rocket Elevators Logo"), index_path, :class => "logo float-left" %>

          <div class="navbar-collapse collapse float-right nav-main-collapse">
            <nav class="nav-main">
              <ul id="topMain" class="nav nav-pills nav-main nav-onepage">
                <li class="active"><!-- HOME -->
                  <%= link_to 'HOME', index_path %>
                </li>
                <li class="dropdown"><!-- SERVICES -->  
                  <%= link_to 'SERVICES', index_path(anchor: "services") %>
                  <ul class="dropdown-menu">
                    <li>
                      <%= link_to 'RESIDENTIAL', residential_path %>
                    </li>
                    <li>
                      <%= link_to 'CORPORATE', corporate_path %>
                    </li>
                    <li>
                      <%= link_to 'GET QUOTE', quoteform_path %>
                    </li>
                  </ul>
                </li>
                <li><!-- WORK -->
                  <%= link_to 'PORTFOLIO', index_path(anchor: "work") %>
                </li>
                <li><!-- NEWS -->
                  <%= link_to 'NEWS', index_path(anchor: "news") %>
                </li>
                <li><!-- CLIENTS -->
                  <%= link_to 'CLIENTS', index_path(anchor: "customers") %>
                </li>
                <li><!-- CONTACT -->
                  <%= link_to 'CONTACT', index_path(anchor: "contact") %>
                </li>
                <li><!-- intervention -->
                  <%= link_to 'INTERVENTION', interventions_path %>
                </li>
                  <li>
                    <%= link_to 'LOGIN', login_path %>
                  </li>
              </ul>
            </nav>
          </div>
        </div>
      </header>
      <!-- /Top Nav -->
    </div>

    <div id="wrapper">
      <script> var plugin_path = 'assets/javascripts/plugins/'; </script>

      <!--
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      -->

      <%= yield %>

    	<!-- FOOTER -->
			<footer id="footer">
				<div class="container-fluid">
					<div class="row">
						<!-- col #1 -->
						<div class="col-md-8">
							<h3 class="letter-spacing-1">WHY US?</h3>
							<!-- Small Description -->
							<p>
								Ask our customers and you will know why you will want our elevators. <br />
								Alternatively, call us and we'll answer your questions.
							</p>
							<h2>(581) 701-0303</h2>
						</div>
						<!-- /col #1 -->
						<!-- col #2 -->
						<div class="col-md-4">
							<h3 class="letter-spacing-1">KEEP IN TOUCH</h3>
							<!-- Newsletter Form -->
							<p>Subscribe to Our (non-existant) Newsletter to get Important News & Offers (to come)</p>
							<form class="validate" action="php/newsletter.php" method="post" data-success="Subscribed! Thank you!" data-toastr-position="bottom-right">
								<div class="input-group">
									<span class="input-group-addon"><i class="fa fa-envelope"></i></span>
									<input type="email" id="email" name="email" class="form-control required" placeholder="Enter your Email">
									<span class="input-group-btn">
										<button class="btn btn-success" type="submit">Subscribe</button>
									</span>
								</div>
							</form>
							<!-- /Newsletter Form -->
						</div>
						<!-- /col #2 -->
					</div>
				</div>
				<div class="copyright">
					<div class="container">
						<ul class="float-right m-0 list-inline mobile-block">
							<li>Terms &amp; Conditions</li>
							<li>&bull;</li>
							<li>Privacy</li>
						</ul>
						&copy; All Rights Reserved, Rocket Elevators LTD
					</div>
				</div>
			</footer>
			<!-- /FOOTER -->
		</div>
		<!-- /wrapper -->

		<!-- SCROLL TO TOP -->
		<a href="#" id="toTop"></a>

		<!-- PRELOADER -->
		<div id="preloader">
			<div class="inner">
				<span class="loader"></span>
			</div>
		</div><!-- /PRELOADER -->

		<!-- JAVASCRIPT FILES -->
    <%= javascript_include_tag "scripts" %>
  
  
  </body>
</html>